# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-28 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', django_countries.fields.CountryField(max_length=2)),
                ('destiny', django_countries.fields.CountryField(max_length=2)),
                ('dateFly', models.DateField()),
                ('dateReturn', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('priceTotal', models.IntegerField()),
                ('url', models.URLField()),
                ('urlImage', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('widthProduct', models.IntegerField()),
                ('weigthProduct', models.IntegerField()),
                ('lengthProduct', models.IntegerField()),
                ('heigthProduct', models.IntegerField()),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('benefit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField(unique=True)),
                ('totalPrice', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberSale', models.IntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('detail', models.TextField(max_length=500)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltApp.Quotation')),
            ],
        ),
        migrations.CreateModel(
            name='UserLt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=128)),
                ('commune', models.CharField(max_length=128)),
                ('cardNumber', models.BigIntegerField(unique=True)),
                ('expirationDate', models.CharField(max_length=5)),
                ('verificationNumber', models.IntegerField()),
                ('userOrigin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='traveller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltApp.UserLt'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='userLtQ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltApp.UserLt'),
        ),
        migrations.AddField(
            model_name='publication',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltApp.Quotation'),
        ),
        migrations.AddField(
            model_name='product',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltApp.Quotation'),
        ),
        migrations.AddField(
            model_name='flight',
            name='traveller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltApp.UserLt'),
        ),
    ]
